name: Build app
run-name: build react app to dist/
on:
  push:
    tags:
      - v*
jobs:
  build-app:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.upload-dist.outputs.artifact-id }}
    steps:
      - name: setup nodejs
        uses: actions/setup-node@v6
        with:
          node_version: "26.4.0"
      - name: get source
        uses: actions/checkout@v7
      - name: install nodejs deps
        run: npm install
      - name: build app
        run: npm run build
      - name: Save artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-result
          id: upload-dist
          path: dist/
  on-success:
    name: "Build image"
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        run: echo -n ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io --username ${{github.actor}} --password-stdin
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{needs.build-app.outputs.output1}}
      - name: Build image
        run: docker build -t ghcr.io/${{github.repository}}:latest build-result/
      - name: Push image to ghcr
        run: docker push ghcr.io/${{github.repository}}:latest