name: Build image
run-name: Build image to ghcr.io
on:
  workflow_run:
    workflows: ["Build app"]
    types:
      - completed
jobs:
  on-success:
    if: ${{github.event.workflow_run.conclusion == 'success'}}
    name: "Build image"
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        run: echo -n ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: build-result
      - name: Build image
        run: docker build -t ghcr.io/${{github.repository}}:latest build-result/
      - name: Push image to ghcr
        run: docker push ghcr.io/${{github.repository}}:latest

