name: Build app
run-name: ${{github.event.head_commit.message}}
on:
  push:
    tags:
      - v*
jobs:
  build-app:
    name: "Build React App into Distributable"
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.upload-dist.outputs.artifact-id }}
    steps:
      - name: setup nodejs
        uses: actions/setup-node@v6
        with:
          node_version: "26.4.0"
      - name: get source
        uses: actions/checkout@v7
      - name: install nodejs deps
        run: npm install
      - name: build app
        run: npm run build
      - name: Save artifact
        uses: actions/upload-artifact@v7
        with:
          name: build-result
          id: upload-dist
          path: dist/
  release-app:
    name: "Release builded app"
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{needs.build-app.outputs.output1}}
      - name: Release
        uses: softprops/action-gh-release@v3
  on-success:
    name: "Build image"
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Login to ghcr.io
        run: echo -n ${{secrets.GITHUB_TOKEN}} | docker login ghcr.io --username ${{github.actor}} --password-stdin
      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          artifact-ids: ${{needs.build-app.outputs.output1}}
      - name: Create nginx Dockerfile
        run: |
          cat << 'EOF' > Dockerfile
          FROM nginx:alpine
          COPY . /usr/share/nginx/html
          EOF
      - name: Build image
        run: docker build -t ghcr.io/${{github.repository}}:latest .
      - name: Push image to ghcr
        run: docker push ghcr.io/${{github.repository}}:latest
  deploy-image:
    name: "Deploy image into server"
    needs: on-success
    runs-on: ubuntu-latest
    steps:
      - name: Pull image from ghcr
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          script: |
            docker pull ghcr.io/${{github.repository}}:latest
            docker rm -f frontend-app
            docker run -d -p 9012:80 --name frontend-app ghcr.io/${{github.repository}}:latest